logging.level:
  root: INFO
  org.springframework: INFO
  de.thberger: DEBUG

stashserver:
      base-url: https://src.openvz.org
      username:
      password:
      filter:
       author: apavlenko
      projects:
       -
        name: OVZ
        repos: openvz-docs



